# Generated by Django 3.1.2 on 2021-02-01 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trans_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_symbol', models.CharField(max_length=250)),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('Trans_symbol', 'Type')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Accno', models.IntegerField()),
                ('Dfield', models.DateField(default=datetime.date.today)),
                ('Amount', models.IntegerField()),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kiosk.trans_type')),
            ],
        ),
    ]
